apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cf-tunnel
  name: tunnel-api-zt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cf-tunnel
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cf-tunnel
    spec:
      containers:
        - args:
            - tunnel
            - --config
            - /opt/zt/config/config.yaml
            - run
          image: cloudflare/cloudflared:latest
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /ready
              port: 2000
            initialDelaySeconds: 10
            periodSeconds: 10
          name: tunnel
          ports:
            - containerPort: 2000
              name: http-metrics
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
          volumeMounts:
            - mountPath: /opt/zt/config
              name: config
              readOnly: true
            - mountPath: /opt/zt/creds
              name: creds
              readOnly: true
      volumes:
        - secret:
            secretName: tunnel-creds
          name: creds
        - configMap:
            name: tunnel-config
          name: config